package com.lbcom.dadelion.bigbin.dao;

import com.lbcom.dadelion.bigbin.model.BZUser;
import com.lbcom.dadelion.bigbin.model.BZUserExample;
import com.lbcom.dadelion.common.base.Dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BZUserDao extends Dao<BZUser>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int countByExample(BZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int deleteByExample(BZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int deleteByPrimaryKey(String xlh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int insert(BZUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int insertSelective(BZUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    List<BZUser> selectByExample(BZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    List<BZUser> selectByPrimaryKey(String xlh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") BZUser record, @Param("example") BZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int updateByExample(@Param("record") BZUser record, @Param("example") BZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int updateByPrimaryKeySelective(BZUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_z_user
     *
     * @mbggenerated Fri Apr 08 12:21:30 CST 2016
     */
    int updateByPrimaryKey(BZUser record);
    List<BZUser> selectByMap(HashMap<String, Object> map);
}