package com.lbcom.dadelion.trysomething.model;

import java.util.ArrayList;
import java.util.List;

public class BQjCdExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public BQjCdExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXhIsNull() {
            addCriterion("XH is null");
            return (Criteria) this;
        }

        public Criteria andXhIsNotNull() {
            addCriterion("XH is not null");
            return (Criteria) this;
        }

        public Criteria andXhEqualTo(Long value) {
            addCriterion("XH =", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotEqualTo(Long value) {
            addCriterion("XH <>", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThan(Long value) {
            addCriterion("XH >", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThanOrEqualTo(Long value) {
            addCriterion("XH >=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThan(Long value) {
            addCriterion("XH <", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThanOrEqualTo(Long value) {
            addCriterion("XH <=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhIn(List<Long> values) {
            addCriterion("XH in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotIn(List<Long> values) {
            addCriterion("XH not in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhBetween(Long value1, Long value2) {
            addCriterion("XH between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotBetween(Long value1, Long value2) {
            addCriterion("XH not between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andFjdIsNull() {
            addCriterion("FJD is null");
            return (Criteria) this;
        }

        public Criteria andFjdIsNotNull() {
            addCriterion("FJD is not null");
            return (Criteria) this;
        }

        public Criteria andFjdEqualTo(String value) {
            addCriterion("FJD =", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotEqualTo(String value) {
            addCriterion("FJD <>", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdGreaterThan(String value) {
            addCriterion("FJD >", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdGreaterThanOrEqualTo(String value) {
            addCriterion("FJD >=", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdLessThan(String value) {
            addCriterion("FJD <", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdLessThanOrEqualTo(String value) {
            addCriterion("FJD <=", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdLike(String value) {
            addCriterion("FJD like", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotLike(String value) {
            addCriterion("FJD not like", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdIn(List<String> values) {
            addCriterion("FJD in", values, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotIn(List<String> values) {
            addCriterion("FJD not in", values, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdBetween(String value1, String value2) {
            addCriterion("FJD between", value1, value2, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotBetween(String value1, String value2) {
            addCriterion("FJD not between", value1, value2, "fjd");
            return (Criteria) this;
        }

        public Criteria andJdywmIsNull() {
            addCriterion("JDYWM is null");
            return (Criteria) this;
        }

        public Criteria andJdywmIsNotNull() {
            addCriterion("JDYWM is not null");
            return (Criteria) this;
        }

        public Criteria andJdywmEqualTo(String value) {
            addCriterion("JDYWM =", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmNotEqualTo(String value) {
            addCriterion("JDYWM <>", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmGreaterThan(String value) {
            addCriterion("JDYWM >", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmGreaterThanOrEqualTo(String value) {
            addCriterion("JDYWM >=", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmLessThan(String value) {
            addCriterion("JDYWM <", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmLessThanOrEqualTo(String value) {
            addCriterion("JDYWM <=", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmLike(String value) {
            addCriterion("JDYWM like", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmNotLike(String value) {
            addCriterion("JDYWM not like", value, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmIn(List<String> values) {
            addCriterion("JDYWM in", values, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmNotIn(List<String> values) {
            addCriterion("JDYWM not in", values, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmBetween(String value1, String value2) {
            addCriterion("JDYWM between", value1, value2, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdywmNotBetween(String value1, String value2) {
            addCriterion("JDYWM not between", value1, value2, "jdywm");
            return (Criteria) this;
        }

        public Criteria andJdzwmIsNull() {
            addCriterion("JDZWM is null");
            return (Criteria) this;
        }

        public Criteria andJdzwmIsNotNull() {
            addCriterion("JDZWM is not null");
            return (Criteria) this;
        }

        public Criteria andJdzwmEqualTo(String value) {
            addCriterion("JDZWM =", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmNotEqualTo(String value) {
            addCriterion("JDZWM <>", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmGreaterThan(String value) {
            addCriterion("JDZWM >", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmGreaterThanOrEqualTo(String value) {
            addCriterion("JDZWM >=", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmLessThan(String value) {
            addCriterion("JDZWM <", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmLessThanOrEqualTo(String value) {
            addCriterion("JDZWM <=", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmLike(String value) {
            addCriterion("JDZWM like", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmNotLike(String value) {
            addCriterion("JDZWM not like", value, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmIn(List<String> values) {
            addCriterion("JDZWM in", values, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmNotIn(List<String> values) {
            addCriterion("JDZWM not in", values, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmBetween(String value1, String value2) {
            addCriterion("JDZWM between", value1, value2, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdzwmNotBetween(String value1, String value2) {
            addCriterion("JDZWM not between", value1, value2, "jdzwm");
            return (Criteria) this;
        }

        public Criteria andJdlxIsNull() {
            addCriterion("JDLX is null");
            return (Criteria) this;
        }

        public Criteria andJdlxIsNotNull() {
            addCriterion("JDLX is not null");
            return (Criteria) this;
        }

        public Criteria andJdlxEqualTo(Short value) {
            addCriterion("JDLX =", value, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxNotEqualTo(Short value) {
            addCriterion("JDLX <>", value, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxGreaterThan(Short value) {
            addCriterion("JDLX >", value, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxGreaterThanOrEqualTo(Short value) {
            addCriterion("JDLX >=", value, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxLessThan(Short value) {
            addCriterion("JDLX <", value, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxLessThanOrEqualTo(Short value) {
            addCriterion("JDLX <=", value, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxIn(List<Short> values) {
            addCriterion("JDLX in", values, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxNotIn(List<Short> values) {
            addCriterion("JDLX not in", values, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxBetween(Short value1, Short value2) {
            addCriterion("JDLX between", value1, value2, "jdlx");
            return (Criteria) this;
        }

        public Criteria andJdlxNotBetween(Short value1, Short value2) {
            addCriterion("JDLX not between", value1, value2, "jdlx");
            return (Criteria) this;
        }

        public Criteria andGnxIsNull() {
            addCriterion("GNX is null");
            return (Criteria) this;
        }

        public Criteria andGnxIsNotNull() {
            addCriterion("GNX is not null");
            return (Criteria) this;
        }

        public Criteria andGnxEqualTo(String value) {
            addCriterion("GNX =", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxNotEqualTo(String value) {
            addCriterion("GNX <>", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxGreaterThan(String value) {
            addCriterion("GNX >", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxGreaterThanOrEqualTo(String value) {
            addCriterion("GNX >=", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxLessThan(String value) {
            addCriterion("GNX <", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxLessThanOrEqualTo(String value) {
            addCriterion("GNX <=", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxLike(String value) {
            addCriterion("GNX like", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxNotLike(String value) {
            addCriterion("GNX not like", value, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxIn(List<String> values) {
            addCriterion("GNX in", values, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxNotIn(List<String> values) {
            addCriterion("GNX not in", values, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxBetween(String value1, String value2) {
            addCriterion("GNX between", value1, value2, "gnx");
            return (Criteria) this;
        }

        public Criteria andGnxNotBetween(String value1, String value2) {
            addCriterion("GNX not between", value1, value2, "gnx");
            return (Criteria) this;
        }

        public Criteria andYmhIsNull() {
            addCriterion("YMH is null");
            return (Criteria) this;
        }

        public Criteria andYmhIsNotNull() {
            addCriterion("YMH is not null");
            return (Criteria) this;
        }

        public Criteria andYmhEqualTo(String value) {
            addCriterion("YMH =", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhNotEqualTo(String value) {
            addCriterion("YMH <>", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhGreaterThan(String value) {
            addCriterion("YMH >", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhGreaterThanOrEqualTo(String value) {
            addCriterion("YMH >=", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhLessThan(String value) {
            addCriterion("YMH <", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhLessThanOrEqualTo(String value) {
            addCriterion("YMH <=", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhLike(String value) {
            addCriterion("YMH like", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhNotLike(String value) {
            addCriterion("YMH not like", value, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhIn(List<String> values) {
            addCriterion("YMH in", values, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhNotIn(List<String> values) {
            addCriterion("YMH not in", values, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhBetween(String value1, String value2) {
            addCriterion("YMH between", value1, value2, "ymh");
            return (Criteria) this;
        }

        public Criteria andYmhNotBetween(String value1, String value2) {
            addCriterion("YMH not between", value1, value2, "ymh");
            return (Criteria) this;
        }

        public Criteria andXspmIsNull() {
            addCriterion("XSPM is null");
            return (Criteria) this;
        }

        public Criteria andXspmIsNotNull() {
            addCriterion("XSPM is not null");
            return (Criteria) this;
        }

        public Criteria andXspmEqualTo(Short value) {
            addCriterion("XSPM =", value, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmNotEqualTo(Short value) {
            addCriterion("XSPM <>", value, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmGreaterThan(Short value) {
            addCriterion("XSPM >", value, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmGreaterThanOrEqualTo(Short value) {
            addCriterion("XSPM >=", value, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmLessThan(Short value) {
            addCriterion("XSPM <", value, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmLessThanOrEqualTo(Short value) {
            addCriterion("XSPM <=", value, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmIn(List<Short> values) {
            addCriterion("XSPM in", values, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmNotIn(List<Short> values) {
            addCriterion("XSPM not in", values, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmBetween(Short value1, Short value2) {
            addCriterion("XSPM between", value1, value2, "xspm");
            return (Criteria) this;
        }

        public Criteria andXspmNotBetween(Short value1, Short value2) {
            addCriterion("XSPM not between", value1, value2, "xspm");
            return (Criteria) this;
        }

        public Criteria andSfxsIsNull() {
            addCriterion("SFXS is null");
            return (Criteria) this;
        }

        public Criteria andSfxsIsNotNull() {
            addCriterion("SFXS is not null");
            return (Criteria) this;
        }

        public Criteria andSfxsEqualTo(Short value) {
            addCriterion("SFXS =", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsNotEqualTo(Short value) {
            addCriterion("SFXS <>", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsGreaterThan(Short value) {
            addCriterion("SFXS >", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsGreaterThanOrEqualTo(Short value) {
            addCriterion("SFXS >=", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsLessThan(Short value) {
            addCriterion("SFXS <", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsLessThanOrEqualTo(Short value) {
            addCriterion("SFXS <=", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsIn(List<Short> values) {
            addCriterion("SFXS in", values, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsNotIn(List<Short> values) {
            addCriterion("SFXS not in", values, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsBetween(Short value1, Short value2) {
            addCriterion("SFXS between", value1, value2, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsNotBetween(Short value1, Short value2) {
            addCriterion("SFXS not between", value1, value2, "sfxs");
            return (Criteria) this;
        }

        public Criteria andXssxIsNull() {
            addCriterion("XSSX is null");
            return (Criteria) this;
        }

        public Criteria andXssxIsNotNull() {
            addCriterion("XSSX is not null");
            return (Criteria) this;
        }

        public Criteria andXssxEqualTo(Short value) {
            addCriterion("XSSX =", value, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxNotEqualTo(Short value) {
            addCriterion("XSSX <>", value, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxGreaterThan(Short value) {
            addCriterion("XSSX >", value, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxGreaterThanOrEqualTo(Short value) {
            addCriterion("XSSX >=", value, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxLessThan(Short value) {
            addCriterion("XSSX <", value, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxLessThanOrEqualTo(Short value) {
            addCriterion("XSSX <=", value, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxIn(List<Short> values) {
            addCriterion("XSSX in", values, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxNotIn(List<Short> values) {
            addCriterion("XSSX not in", values, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxBetween(Short value1, Short value2) {
            addCriterion("XSSX between", value1, value2, "xssx");
            return (Criteria) this;
        }

        public Criteria andXssxNotBetween(Short value1, Short value2) {
            addCriterion("XSSX not between", value1, value2, "xssx");
            return (Criteria) this;
        }

        public Criteria andJdcsIsNull() {
            addCriterion("JDCS is null");
            return (Criteria) this;
        }

        public Criteria andJdcsIsNotNull() {
            addCriterion("JDCS is not null");
            return (Criteria) this;
        }

        public Criteria andJdcsEqualTo(String value) {
            addCriterion("JDCS =", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsNotEqualTo(String value) {
            addCriterion("JDCS <>", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsGreaterThan(String value) {
            addCriterion("JDCS >", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsGreaterThanOrEqualTo(String value) {
            addCriterion("JDCS >=", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsLessThan(String value) {
            addCriterion("JDCS <", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsLessThanOrEqualTo(String value) {
            addCriterion("JDCS <=", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsLike(String value) {
            addCriterion("JDCS like", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsNotLike(String value) {
            addCriterion("JDCS not like", value, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsIn(List<String> values) {
            addCriterion("JDCS in", values, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsNotIn(List<String> values) {
            addCriterion("JDCS not in", values, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsBetween(String value1, String value2) {
            addCriterion("JDCS between", value1, value2, "jdcs");
            return (Criteria) this;
        }

        public Criteria andJdcsNotBetween(String value1, String value2) {
            addCriterion("JDCS not between", value1, value2, "jdcs");
            return (Criteria) this;
        }

        public Criteria andTbljIsNull() {
            addCriterion("TBLJ is null");
            return (Criteria) this;
        }

        public Criteria andTbljIsNotNull() {
            addCriterion("TBLJ is not null");
            return (Criteria) this;
        }

        public Criteria andTbljEqualTo(String value) {
            addCriterion("TBLJ =", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljNotEqualTo(String value) {
            addCriterion("TBLJ <>", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljGreaterThan(String value) {
            addCriterion("TBLJ >", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljGreaterThanOrEqualTo(String value) {
            addCriterion("TBLJ >=", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljLessThan(String value) {
            addCriterion("TBLJ <", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljLessThanOrEqualTo(String value) {
            addCriterion("TBLJ <=", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljLike(String value) {
            addCriterion("TBLJ like", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljNotLike(String value) {
            addCriterion("TBLJ not like", value, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljIn(List<String> values) {
            addCriterion("TBLJ in", values, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljNotIn(List<String> values) {
            addCriterion("TBLJ not in", values, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljBetween(String value1, String value2) {
            addCriterion("TBLJ between", value1, value2, "tblj");
            return (Criteria) this;
        }

        public Criteria andTbljNotBetween(String value1, String value2) {
            addCriterion("TBLJ not between", value1, value2, "tblj");
            return (Criteria) this;
        }

        public Criteria andYlzd1IsNull() {
            addCriterion("YLZD1 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd1IsNotNull() {
            addCriterion("YLZD1 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd1EqualTo(String value) {
            addCriterion("YLZD1 =", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotEqualTo(String value) {
            addCriterion("YLZD1 <>", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1GreaterThan(String value) {
            addCriterion("YLZD1 >", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD1 >=", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1LessThan(String value) {
            addCriterion("YLZD1 <", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1LessThanOrEqualTo(String value) {
            addCriterion("YLZD1 <=", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1Like(String value) {
            addCriterion("YLZD1 like", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotLike(String value) {
            addCriterion("YLZD1 not like", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1In(List<String> values) {
            addCriterion("YLZD1 in", values, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotIn(List<String> values) {
            addCriterion("YLZD1 not in", values, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1Between(String value1, String value2) {
            addCriterion("YLZD1 between", value1, value2, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotBetween(String value1, String value2) {
            addCriterion("YLZD1 not between", value1, value2, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd2IsNull() {
            addCriterion("YLZD2 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd2IsNotNull() {
            addCriterion("YLZD2 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd2EqualTo(String value) {
            addCriterion("YLZD2 =", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotEqualTo(String value) {
            addCriterion("YLZD2 <>", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2GreaterThan(String value) {
            addCriterion("YLZD2 >", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD2 >=", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2LessThan(String value) {
            addCriterion("YLZD2 <", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2LessThanOrEqualTo(String value) {
            addCriterion("YLZD2 <=", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2Like(String value) {
            addCriterion("YLZD2 like", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotLike(String value) {
            addCriterion("YLZD2 not like", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2In(List<String> values) {
            addCriterion("YLZD2 in", values, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotIn(List<String> values) {
            addCriterion("YLZD2 not in", values, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2Between(String value1, String value2) {
            addCriterion("YLZD2 between", value1, value2, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotBetween(String value1, String value2) {
            addCriterion("YLZD2 not between", value1, value2, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd3IsNull() {
            addCriterion("YLZD3 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd3IsNotNull() {
            addCriterion("YLZD3 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd3EqualTo(String value) {
            addCriterion("YLZD3 =", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotEqualTo(String value) {
            addCriterion("YLZD3 <>", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3GreaterThan(String value) {
            addCriterion("YLZD3 >", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD3 >=", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3LessThan(String value) {
            addCriterion("YLZD3 <", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3LessThanOrEqualTo(String value) {
            addCriterion("YLZD3 <=", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3Like(String value) {
            addCriterion("YLZD3 like", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotLike(String value) {
            addCriterion("YLZD3 not like", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3In(List<String> values) {
            addCriterion("YLZD3 in", values, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotIn(List<String> values) {
            addCriterion("YLZD3 not in", values, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3Between(String value1, String value2) {
            addCriterion("YLZD3 between", value1, value2, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotBetween(String value1, String value2) {
            addCriterion("YLZD3 not between", value1, value2, "ylzd3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B_QJ_CD
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 11 13:41:03 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}