package com.lbcom.dadelion.trysomething.model;

public class BQjCd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.XH
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private Long xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.FJD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String fjd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.JDYWM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String jdywm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.JDZWM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String jdzwm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.JDLX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private Short jdlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.GNX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String gnx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.YMH
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String ymh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.XSPM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private Short xspm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.SFXS
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private Short sfxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.XSSX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private Short xssx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.JDCS
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String jdcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.TBLJ
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String tblj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.YLZD1
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String ylzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.YLZD2
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String ylzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_CD.YLZD3
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    private String ylzd3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.XH
     *
     * @return the value of B_QJ_CD.XH
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public Long getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.XH
     *
     * @param xh the value for B_QJ_CD.XH
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setXh(Long xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.FJD
     *
     * @return the value of B_QJ_CD.FJD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getFjd() {
        return fjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.FJD
     *
     * @param fjd the value for B_QJ_CD.FJD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setFjd(String fjd) {
        this.fjd = fjd == null ? null : fjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.JDYWM
     *
     * @return the value of B_QJ_CD.JDYWM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getJdywm() {
        return jdywm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.JDYWM
     *
     * @param jdywm the value for B_QJ_CD.JDYWM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setJdywm(String jdywm) {
        this.jdywm = jdywm == null ? null : jdywm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.JDZWM
     *
     * @return the value of B_QJ_CD.JDZWM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getJdzwm() {
        return jdzwm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.JDZWM
     *
     * @param jdzwm the value for B_QJ_CD.JDZWM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setJdzwm(String jdzwm) {
        this.jdzwm = jdzwm == null ? null : jdzwm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.JDLX
     *
     * @return the value of B_QJ_CD.JDLX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public Short getJdlx() {
        return jdlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.JDLX
     *
     * @param jdlx the value for B_QJ_CD.JDLX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setJdlx(Short jdlx) {
        this.jdlx = jdlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.GNX
     *
     * @return the value of B_QJ_CD.GNX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getGnx() {
        return gnx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.GNX
     *
     * @param gnx the value for B_QJ_CD.GNX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setGnx(String gnx) {
        this.gnx = gnx == null ? null : gnx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.YMH
     *
     * @return the value of B_QJ_CD.YMH
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getYmh() {
        return ymh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.YMH
     *
     * @param ymh the value for B_QJ_CD.YMH
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setYmh(String ymh) {
        this.ymh = ymh == null ? null : ymh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.XSPM
     *
     * @return the value of B_QJ_CD.XSPM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public Short getXspm() {
        return xspm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.XSPM
     *
     * @param xspm the value for B_QJ_CD.XSPM
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setXspm(Short xspm) {
        this.xspm = xspm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.SFXS
     *
     * @return the value of B_QJ_CD.SFXS
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public Short getSfxs() {
        return sfxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.SFXS
     *
     * @param sfxs the value for B_QJ_CD.SFXS
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setSfxs(Short sfxs) {
        this.sfxs = sfxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.XSSX
     *
     * @return the value of B_QJ_CD.XSSX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public Short getXssx() {
        return xssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.XSSX
     *
     * @param xssx the value for B_QJ_CD.XSSX
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setXssx(Short xssx) {
        this.xssx = xssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.JDCS
     *
     * @return the value of B_QJ_CD.JDCS
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getJdcs() {
        return jdcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.JDCS
     *
     * @param jdcs the value for B_QJ_CD.JDCS
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setJdcs(String jdcs) {
        this.jdcs = jdcs == null ? null : jdcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.TBLJ
     *
     * @return the value of B_QJ_CD.TBLJ
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getTblj() {
        return tblj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.TBLJ
     *
     * @param tblj the value for B_QJ_CD.TBLJ
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setTblj(String tblj) {
        this.tblj = tblj == null ? null : tblj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.YLZD1
     *
     * @return the value of B_QJ_CD.YLZD1
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getYlzd1() {
        return ylzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.YLZD1
     *
     * @param ylzd1 the value for B_QJ_CD.YLZD1
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setYlzd1(String ylzd1) {
        this.ylzd1 = ylzd1 == null ? null : ylzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.YLZD2
     *
     * @return the value of B_QJ_CD.YLZD2
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getYlzd2() {
        return ylzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.YLZD2
     *
     * @param ylzd2 the value for B_QJ_CD.YLZD2
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setYlzd2(String ylzd2) {
        this.ylzd2 = ylzd2 == null ? null : ylzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_CD.YLZD3
     *
     * @return the value of B_QJ_CD.YLZD3
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public String getYlzd3() {
        return ylzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_CD.YLZD3
     *
     * @param ylzd3 the value for B_QJ_CD.YLZD3
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    public void setYlzd3(String ylzd3) {
        this.ylzd3 = ylzd3 == null ? null : ylzd3.trim();
    }
}