package com.lbcom.dadelion.trysomething.dao;

import com.lbcom.dadelion.common.base.Dao;
import com.lbcom.dadelion.trysomething.model.BQjCd;
import com.lbcom.dadelion.trysomething.model.BQjCdExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface BQjCdDao extends Dao<BQjCd>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    int countByExample(BQjCdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    int deleteByExample(BQjCdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    int insert(BQjCd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    int insertSelective(BQjCd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    List<BQjCd> selectByExample(BQjCdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") BQjCd record, @Param("example") BQjCdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_QJ_CD
     *
     * @mbggenerated Fri Mar 11 13:41:03 CST 2016
     */
    int updateByExample(@Param("record") BQjCd record, @Param("example") BQjCdExample example);

	List<BQjCd> selectByparams(Map<String, Object> map);
}