package com.lbcom.dadelion.bigbincm.model;

public class BQjXtpz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_qj_xtpz.id
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_qj_xtpz.name
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_qj_xtpz.name_cn
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    private String nameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_qj_xtpz.val
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    private String val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_qj_xtpz.expand
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    private String expand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_qj_xtpz.description
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_qj_xtpz.id
     *
     * @return the value of b_qj_xtpz.id
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_qj_xtpz.id
     *
     * @param id the value for b_qj_xtpz.id
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_qj_xtpz.name
     *
     * @return the value of b_qj_xtpz.name
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_qj_xtpz.name
     *
     * @param name the value for b_qj_xtpz.name
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_qj_xtpz.name_cn
     *
     * @return the value of b_qj_xtpz.name_cn
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public String getNameCn() {
        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_qj_xtpz.name_cn
     *
     * @param nameCn the value for b_qj_xtpz.name_cn
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn == null ? null : nameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_qj_xtpz.val
     *
     * @return the value of b_qj_xtpz.val
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_qj_xtpz.val
     *
     * @param val the value for b_qj_xtpz.val
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_qj_xtpz.expand
     *
     * @return the value of b_qj_xtpz.expand
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public String getExpand() {
        return expand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_qj_xtpz.expand
     *
     * @param expand the value for b_qj_xtpz.expand
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public void setExpand(String expand) {
        this.expand = expand == null ? null : expand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_qj_xtpz.description
     *
     * @return the value of b_qj_xtpz.description
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_qj_xtpz.description
     *
     * @param description the value for b_qj_xtpz.description
     *
     * @mbggenerated Thu Aug 17 15:24:55 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}